// really slow dependency updates, please
pullRequests.frequency = "90 days"

commits.message = "bump: ${artifactName} ${nextVersion} (was ${currentVersion})"

postUpdateHooks = [
  {
    groupId = "com.google.googlejavaformat"
    artifactId = "google-java-format"
    command = ["bash", "scripts/update-google-java-format-runtime.sh"]
    commitMessage = "Update google-java-format runtime mapping"
  }
]
