sudo: false
language: scala
jdk: oraclejdk8

jobs:
  include:
     - stage: test
       script: sbt scripted

     - stage: publish
       script:
        - sbt publish
        - sbt ^^0.13.18 ++2.10.7 publish

stages:
  # runs on master commits and PRs
  - name: test
    if: NOT tag =~ ^v

  # runs on main repo master commits or version-tagged commits
  - name: publish
    if: repo = sbt/sbt-java-formatter AND ( ( branch = master AND type = push ) OR tag =~ ^v )


before_cache:
  - find $HOME/.ivy2/ -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt   -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

env:
  global:
    # encrypt with: travis encrypt BINTRAY_USER=...
    - secure: "i8q/3/RXpPLJ4MrUtk4jT5RtLTl0N8tKu3ny+mjhWs8bXafWwSkmbRkQuwKB/8vvvAjAFuDvYHsrnXBRnIUs4wenHxp+1FQDBCgnajpLcmTy7OTyMnIHOU8mboW+pxlk4LiSL4qnT7FYZ7NeYQr1kYmQ1y9IETiEFhi4m+kRzJUB7+fU0rDFTo1cMe2hzZ3iihYD8JZiGnFAW9yjFlZyWjahql4LE7qUSMCcQ6VnSE/wGT0wq5MNvlZWR5kLKDp4L1S1lz+S18HVBT5Mnj66RQS3CEsqNxQoqbIckRG//O2I/UV4BsYicZr6TG3G40G1PmEK5chD8M/IEKuwpgts2rQ9ZAtIqYry0ETrp/Vq3lPxWKj4A6AJ4d+hxH0M7v9IO79nCf8DupBHNqZAeFSbwk9eXvI/3LGM9w5TZMe5Pnrkcx/f79vbZo3X/pTX12tdWZxPRyf3kVn6oX4uHtGtDTjJvF1LAWgnRaFm3lVlJ0TW3o1gjtW/0xHww8lpPJvLnh4EjXqsJuX3MG4PBx5rswmYrQ9ZT97gCWD+hfZO+TnyMcFuDIHuZz1KYe9a4KM2ow23vRFXAy4M3lvh98xpz672wuddwvBao8eu/yeH2V+nI3BNqLaEuGxB4o3MaMoDWcNjBZ+EaMy5KhGl9yDu7VaeBv/z87i4cRsarz0Y9hg="
    # encrypt with: travis encrypt BINTRAY_PASS=...
    - secure: "cNuEwcTtMEjQxYN+5lMkNu/1nfvXolsejRBMxObUByYe0TUPLTBWAudemC0Vxmp/ij3qMPXNQuag4I9QE2yM3uOudLevSLQlDHGUVIGrJyWX0o5AYzjrws7pdop/VAHKg0IcabVJsJHlT9IJ+ZeLmyTCvCuu4bfjd+ztpFN3ogp+EouDOkjAg2LhILHNDJjBuleJhfDTp7CmVuydrRD5W+DjZTE3LPYg+vd2fHV9lvzuts0hFXE1rsiOIIkmSxuIM8cFHfYYSSveRrIzhw7XIykPfX/tBdg88TNgKlJOAXGuORnTrrT2dn5sKEFgPbpKx3J481/UOYQ4s4W2bVBIbsv7zTYrht7+9crTApOA2frtgTipcCA4avtImYCg4Qk/f6CAnzdhhblwECBdFSQmsbyn29e/v+DkdXyHUONib4FH9rQcYgMuEfDkh1Fgmohc7h1N5fcz4gWLOfNPwHu+3Du51yl/ucCyfZ04elWUpCOwkmB00XRREX2vP2ElCIftIePye5xetylvJUztcBqQYYi6kD+J1d5OnFYmbDj0PlR/0QJnlOqKXe8cP707EKnuS1AF/KNLA2B1nl2BIWexLX/5Gk9rpCnRmZMQUakMfKp5Awt4W0ijs4eFdWLrmb2xC0gvBm2z54ITxy28b9+fEAcR95Q6uqNgsulY8RGlNB4="
